apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5-dev
  labels:
    app: yolo5-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo5-dev
  template:
    metadata:
        labels:
          app: yolo5-dev
    spec:
      containers:
      - name: yolo5-dev
        image: IMG_URL
        env:
          - name: secret_name
            value: "roman-secret-dev-tg"
        ports:
        - containerPort: 8080
---
# yolo-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: yolo5-dev-svc
spec:
  selector:
    app: yolo5-dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yolo5-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yolo5-dev
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

